INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (1, 'template1', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO SECTION (ID, TEMPLATE_ID, NAME, DESCRIPTION, SECTION_TYPE, POSITION, CREATED_DATE) VALUES (1, 1, 'Comunicacion', 'Capacidades del evaluado para comunicarse con su equipo', 0, 1,  PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ITEM_TEMPLATE(ID, SECTION_ID, TITLE, DESCRIPTION, ITEM_TYPE, POSITION, CREATED_DATE) VALUES (1, 1, 'Claridad', 'Expresa claramente sus ideas', 0, 1,  PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ITEM_TEMPLATE(ID, SECTION_ID, TITLE, DESCRIPTION, ITEM_TYPE, POSITION, CREATED_DATE) VALUES (2, 1, 'Escucha', 'Deja expresar las opiniones de los demas sin imponer sus ideas', 0, 2,  PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO SECTION (ID, TEMPLATE_ID, NAME, DESCRIPTION, SECTION_TYPE, POSITION, CREATED_DATE) VALUES (2, 1, 'Liderazgo', 'Capacidades del evaluado para liderar a su equipo', 0, 2,  PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO ITEM_TEMPLATE(ID, SECTION_ID, TITLE, DESCRIPTION, ITEM_TYPE, POSITION, CREATED_DATE) VALUES (3, 2, 'Motivacion', 'Es bueno motivando al equipo', 0, 1,  PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));


INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (2, 'template2', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (3, 'template3', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (4, 'template4', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (5, 'template5', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (6, 'template6', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (7, 'template7', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (8, 'template8', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (9, 'template9', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (10, 'template10', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (11, 'template11', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO EVALUATION_TEMPLATE (ID, TITLE, ID_USER, CREATED_DATE) VALUES (12, 'template12', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
