server:
  port: 0

spring.profiles.include: default

#Propiedades Eureka
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddess: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap.instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
  
#Propiedades de MongoDb
mongodb.dbname: evaluations
spring.data.mongodb.uri: mongodb://localhost:27017/evaluations

#Project service
projects.url: http://projects-service/projects
 
 # Propiedades Kafka
spring.kafka.sslEnabled: false
spring.kafka.properties.sasl.jaas.config: 
spring.kafka.bootstrap-servers: localhost:9092
app.topic.notificationRV: notificationRV.t

# Zipkin
spring.zipkin.base-url: http://localhost:9411/
spring.sleuth.sampler.probability: 1.0
logging.level.org.springframework.cloud.sleuth: DEBUG


