spring.profiles.active: local


# Logging
logging.level:
  root: INFO
  org.springframework.web: INFO
  com.gire.eval360.evaluations: DEBUG

# Actuator
management:
  endpoints:
    web.exposure.include:*
    jmx.exposure.exclude:*