spring.profiles.include: default

server:
  port: 8080

#Propiedades Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  
#Propiedades de MongoDb
mongodb.dbname: heroku_84q7w3sl
spring.data.mongodb.uri: mongodb://heroku_84q7w3sl:scjobarsvf2136fh81svt3efbs@ds023445.mlab.com:23445/heroku_84q7w3sl

#Project service
projects.url: http://projects-service/projects
 
 # Propiedades Kafka
spring.kafka.sslEnabled: true
spring.kafka.bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
spring.kafka.properties.security.protocol: SASL_SSL
spring.kafka.properties.sasl.mechanism: SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
app.topic.notificationRV: ${CLOUDKARAFKA_USERNAME}-notificationRV.t
