spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        type: trace


server:
  port: 9100
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


jwt:
   header: Authorization
   secret: mySecret
   expiration: 604800
   route:
     authentication:
       path: /auth
       refresh: /refresh
       