spring.profiles.include: default

server:
  port: 8080

#Propiedades H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        type: trace
  
#Propiedades Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
       
# Propiedades Kafka
spring.kafka.bootstrap-servers: localhost:9092
