
server:
  port: 8100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
        type: trace


jwt:
   header: Authorization
   secret: mySecret
   expiration: 86400
   route:
     authentication:
       path: /auth
       refresh: /refresh
       