
INSERT INTO AREA (ID, CODE, NAME, DESCRIPTION, CREATED_DATE)
VALUES (1, 10, 'Sistemas', 'Area de Sistemas', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO POSITION (ID, CODE, NAME, DESCRIPTION, CREATED_DATE)
VALUES (1, 10, 'Desarrollador', 'Desarrollador Java', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO POSITION (ID, CODE, NAME, DESCRIPTION, CREATED_DATE)
VALUES (2, 11, 'QA Tester', 'Quality Assurance Tester', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));


INSERT INTO EMPLOYEE (ID, NAME, LASTNAME, BIRTH_DATE, START_DATE, PHOTO,  AREA_ID, POSITION_ID, CREATED_DATE)
VALUES (1, 'Lionel', 'Messi', PARSEDATETIME('24-06-1987', 'dd-MM-yyyy'), PARSEDATETIME('30-06-2018', 'dd-MM-yyyy'), 'Messi', 1, 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO CONTACT_INFO (ID, EMPLOYEE_ID, INTERNAL_NUMBER, TELEPHONE_NUMBER, EMAIL, CREATED_DATE)
VALUES (1, 1, '11302', '1142314242', 'messi@gmail.com', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO ADDRESS (ID, EMPLOYEE_ID, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_DATE)
VALUES (1, 1, 'Calle 10', 'Barcelona', 'Catalunya', '1201', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO EMPLOYEE (ID, NAME, LASTNAME, BIRTH_DATE, START_DATE, PHOTO,  AREA_ID, POSITION_ID, CREATED_DATE)
VALUES (2, 'Sergio', 'Aguero', PARSEDATETIME('02-06-1988', 'dd-MM-yyyy'), PARSEDATETIME('10-06-2018', 'dd-MM-yyyy'), 'Aguero', 1, 2, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO CONTACT_INFO (ID, EMPLOYEE_ID, INTERNAL_NUMBER, TELEPHONE_NUMBER, EMAIL, CREATED_DATE)
VALUES (2, 2, '11303', '11512312313', 'aguero@gmail.com', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));

INSERT INTO ADDRESS (ID, EMPLOYEE_ID, ADDRESS, CITY, STATE, POSTAL_CODE, CREATED_DATE)
VALUES (2, 2, 'Cabido 500', 'Buenos Aires', 'Argentina', '1452', PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
