spring.profiles.include: default

server:
  port: 8080

#Propiedades Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  
#Propiedades de H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.web-allow-others: true
  datasource:
     plataform: h2
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:testdb
     username: sa
     password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        type: trace

 # Propiedades Kafka
spring.kafka.sslEnabled: true
spring.kafka.bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
spring.kafka.properties.security.protocol: SASL_SSL
spring.kafka.properties.sasl.mechanism: SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
app.topic.notificationFP: ${CLOUDKARAFKA_USERNAME}-notificationFP.t
app.topic.notificationRV: ${CLOUDKARAFKA_USERNAME}-notificationRV.t

#Propiedades Servicio Users
users.url: http://AUTH-SERVICE/users
