spring.profiles.include: default

server:
  port: 0

#Propiedades Eureka
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddess: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap.instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
  
#Propiedades Servicios
projects.url: http://projects-service/projects
users.url: http://auth-service/users
evaluations.url: http://evaluations-service/evaluations
templates.url: http://templates-service/evaluationTemplates

#Propiedades de MongoDb
mongodb.dbname: reports
spring.data.mongodb.uri: mongodb://localhost:27017/reports


 # Propiedades Kafka
spring.kafka.sslEnabled: false
spring.kafka.properties.sasl.jaas.config: 
spring.kafka.bootstrap-servers: localhost:9092
spring.kafka.consumer.group-id: reports
app.topic.notificationRV: notificationRV.t
app.topic.notificationReport: notificationReport.t

# Zipkin
spring.zipkin.base-url: http://localhost:9411/
spring.sleuth.sampler.probability: 1
