spring.profiles.active: local


# Zipkin
spring.zipkin.sender.type: kafka

# Logging
logging.level:
  root: ERROR
  org.springframework.web: ERROR
  com.gire.eval360.notifications: DEBUG

# Actuator
management:
  endpoints:
    web.exposure.include:*
    jmx.exposure.exclude:*


#Spring mail SMTP
# spring:
#   mail:
#     default-encoding: UTF-8
#     host: smtp.mailgun.org
#     username: postmaster@sandbox2a7f9db68c014c3b8dd54a51f5bbc233.mailgun.org
#     password: db495f8aada86990c86555c515c037f2-7bce17e5-a2b22118
#     port: 587
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#     protocol: smtp
#     test-connection: false