
server:
  port: 0

#Propiedades Eureka
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddess: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap.instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
  
 
 # Propiedades Kafka
spring.kafka.bootstrap-servers: localhost:9092
app.topic.notificationFP: notificationFP.t
app.topic.notificationRV: notificationRV.t

# Zipkin
spring.zipkin.sender.type: kafka

# Logging
logging.level:
  root: ERROR
  org.springframework.web: ERROR
  com.gire.eval360.notifications: DEBUG

# Actuator
management:
  endpoints:
    web.exposure.include:*
    jmx.exposure.exclude:*
    
#Propiedades Servicio Users, Evaluations
users.url: http://AUTH-SERVICE/users
evaluations.url: http://evaluations/evaluations

#SMTP
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: notifica.eval360@gmail.com
    password: Password3245
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false