spring.profiles.active: local


# Zipkin
spring.zipkin.sender.type: kafka

# Logging
logging.level:
  root: ERROR
  org.springframework.web: ERROR
  com.gire.eval360.notifications: DEBUG

# Actuator
management:
  endpoints:
    web.exposure.include:*
    jmx.exposure.exclude:*


#SMTP
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.sendgrid.net
    username: NotificationApi
    password: SG.FmgRPxuYRUW2BakVwQPlPQ.D7Up8bSs7Vl - tLjnMoIoSmRidmoaYLXe8QKpAVcFek
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false