spring.profiles.active: local


# Zipkin
spring.zipkin.sender.type: kafka

# Logging
logging.level:
  root: ERROR
  org.springframework.web: ERROR
  com.gire.eval360.notifications: DEBUG

# Actuator
management:
  endpoints:
    web.exposure.include:*
    jmx.exposure.exclude:*

