spring.profiles.include: default

server:
  port: 8080

#Propiedades Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

# Propiedades Kafka
spring.kafka.sslEnabled: true
spring.kafka.bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
spring.kafka.properties.security.protocol: SASL_SSL
spring.kafka.properties.sasl.mechanism: SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
spring.kafka.consumer.group-id: ${CLOUDKARAFKA_USERNAME}-notifications
app.topic.notificationFP: ${CLOUDKARAFKA_USERNAME}-notificationFP.t
app.topic.notificationReport: ${CLOUDKARAFKA_USERNAME}-notificationReport.t

    
#Propiedades Servicio Users, Evaluations
users.url: http://AUTH-SERVICE/users
evaluations.url: http://evaluations/evaluations
projects.url: http://projects-service/projects
notifications.url: http://eval-360.cfapps.io

# Misc
application.url: http://localhost:4200

# Spring mail SMTP
spring:
  mail:
    default-encoding: UTF-8
    host: ${SENDGRID_HOST}
    username: ${SENDGRID_USERNAME}
    password: ${SENDGRID_PASSWORD}
    port: ${SENDGRID_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false